### ISSUE TITLE
Seek for Help

### ISSUE THREAD

**Issue by Yawning10** [3it-nano/B1530A_control#1]
Hello！I wonder where to get the wgfmu.lib,it seems not work.   :(

**Comment by PAMouny** [comment]
Hello,
There is a list of libraries/drivers to install in order to able the connection with the B1500.
-NI 488 drivers https://www.ni.com/fr-ca/support/downloads/drivers/download.ni-488-2.html#467646
-IO library suites from Keysigh https://www.keysight.com/ca/en/lib/software-detail/computer-software/io-libraries-suite-downloads-2175637.html
-B1500 drivers https://www.keysight.com/ca/en/lib/software-detail/driver/b1530a-wgfmu-instrument-library--sample-programs-2117445.html.

With all of that installed, you should be able to connect and communicate with the B1500. Make sure you are using a GPIB-USB-HS interface controller from NI as it did not work for other type of GPIB controller.

I'll update the readme file to add these required libraries.

**Comment by Yawning10** [comment]
Thank you for your help!
